name: Deploy to GCP

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Install dependencies
        run: npm install
        
      - name: Build static site
        run: npm run build
        
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: production-artifacts
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v2
        with:
          name: production-artifacts
        
      - name: Deploy to GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > "${HOME}/gcloud.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud.json"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gsutil rsync -r ./build gs://assignment_test
